-- Add per-face comments with support for authenticated and anonymous users.

create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  face_id bigint not null references public.faces(id) on delete cascade,
  user_id uuid null references auth.users(id) on delete cascade default auth.uid(),
  content text not null check (char_length(content) between 1 and 300),
  created_at timestamptz not null default now()
);

create index if not exists comments_face_created_at_idx
  on public.comments (face_id, created_at desc);

alter table public.comments enable row level security;

do $$
declare
  p record;
begin
  for p in
    select policyname
    from pg_policies
    where schemaname = 'public'
      and tablename = 'comments'
  loop
    execute format('drop policy if exists %I on public.comments', p.policyname);
  end loop;
end
$$;

create policy comments_select_all
  on public.comments
  for select
  to anon, authenticated
  using (true);

create policy comments_insert_authenticated_own
  on public.comments
  for insert
  to authenticated
  with check (auth.uid() is not null and auth.uid() = coalesce(user_id, auth.uid()));

create policy comments_insert_anon
  on public.comments
  for insert
  to anon
  with check (auth.uid() is null and user_id is null);
